// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEhgrx3djzU9sFqU7d1lr1J5Z3V0SC3KE',
    appId: '1:61816856359:web:c0fac648612dfc4ea9d302',
    messagingSenderId: '61816856359',
    projectId: 'flutter-notes-26836',
    authDomain: 'flutter-notes-26836.firebaseapp.com',
    storageBucket: 'flutter-notes-26836.appspot.com',
    measurementId: 'G-NWDKEHL6ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMa1tBlcJLd5YIwjorl3O2nd2f2--83wU',
    appId: '1:61816856359:android:0a4215c0b8235f35a9d302',
    messagingSenderId: '61816856359',
    projectId: 'flutter-notes-26836',
    storageBucket: 'flutter-notes-26836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjHcEnwgjq_Y-usCQ-OLFlik8wnbH1zI',
    appId: '1:61816856359:ios:a68ec7d8634692b9a9d302',
    messagingSenderId: '61816856359',
    projectId: 'flutter-notes-26836',
    storageBucket: 'flutter-notes-26836.appspot.com',
    iosClientId: '61816856359-lhag864fupq4mr056cqebde52ggkrhn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjHcEnwgjq_Y-usCQ-OLFlik8wnbH1zI',
    appId: '1:61816856359:ios:5065c60c4aab2949a9d302',
    messagingSenderId: '61816856359',
    projectId: 'flutter-notes-26836',
    storageBucket: 'flutter-notes-26836.appspot.com',
    iosClientId: '61816856359-qli70ltqj50f3riqf60d4v4qqh8k38pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
