name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release --base-href '/notes-app/'
      - uses: bluefireteam/flutter-gh-pages@v7
